{-# LANGUAGE OverloadedStrings #-}

{-|
Module      : Parser.Program.Import
Description : Import system for the Moo programming language
Copyright   : (c) 2025 Moo Language Team
License     : MIT
Maintainer  : joaoduos@gmail.com
Stability   : experimental
Portability : POSIX

= ⚠️  AI-GENERATED CODE - NOT YET HUMAN-REVIEWED ⚠️

This module was automatically generated by AI assistance and has not yet been
thoroughly reviewed or tested by a human developer. Use with caution in
production environments.

= Overview

This module implements a complete import system for the Moo programming language,
allowing programs to reference definitions from other source files. The system
handles file resolution, recursive parsing, conflict detection, and circular
import prevention.

= Import Syntax

The basic syntax for importing a file is:

@
import path/to/file.moo
@

Imports must appear at the beginning of a Moo source file (implementation pending).
Paths can be absolute or relative to the current file.

= Features

* __File Path Resolution__: Resolves relative and absolute paths correctly
* __Recursive Imports__: Automatically processes imports within imported files
* __Circular Detection__: Detects and prevents circular import dependencies
* __Conflict Detection__: Validates that imported definitions don't conflict
* __Error Reporting__: Provides detailed error messages for all failure modes

= Example Usage

Suppose we have the following file structure:

@
src/
  main.moo
  utils/
    math.moo
    list.moo
@

In @main.moo@:

@
import utils\/math.moo
import utils\/list.moo

fun main() -> Int := 
  let result = add(5, multiply(3, 4))
  listLength([1, 2, 3]) + result
@

In @utils\/math.moo@:

@
fun add(x: Int, y: Int) -> Int := x + y
fun multiply(x: Int, y: Int) -> Int := x * y
@

In @utils\/list.moo@:

@
fun listLength(list: List[Int]) -> Int := 
  match list with
  | Nil -> 0
  | Cons(_, rest) -> 1 + listLength(rest)
@

= Implementation Status

[✅] Parse import declarations
[✅] Resolve relative file paths  
[✅] Recursively parse imported files
[✅] Merge imported definitions
[✅] Detect circular imports
[✅] Validate name conflicts
[⚠️]  Track file origins for better error messages (placeholder)
[📋] Integration with main parser (pending)
[📋] Import caching for performance (future optimization)

= Error Handling

The module defines four types of import errors:

* 'FileNotFound': The imported file doesn't exist on disk
* 'CircularImport': A circular import dependency was detected
* 'ParseError': The imported file contains syntax errors
* 'DuplicateDefinition': Two imports define the same name

All errors include detailed context to help diagnose problems.

= Technical Details

== File Resolution Algorithm

1. Take the directory of the current file being parsed
2. Combine it with the import path using '<\/>'
3. Normalize the result to resolve @..@ and @.@ components

== Import Processing Algorithm

1. Resolve each import path relative to the current file
2. Check if the resolved path is in the visited set (circular check)
3. Verify the file exists on disk
4. Read and parse the file contents
5. Recursively process any imports in the imported file
6. Merge definitions, checking for conflicts
7. Add the file to the visited set

== Conflict Detection

The merger checks for name conflicts in:

* Type definitions ('TypeDef')
* Data constructors ('ConstrDef') 
* Global variables ('GlobalDef')
* Constants ('ConstDef')
* Functions ('FunDef')

If any name appears in both programs, a 'DuplicateDefinition' error is returned.

= Future Improvements

* Add file origin tracking to 'Program' for better error messages
* Implement import caching with @Map FilePath Program@
* Add support for selective imports: @import utils.math (add, multiply)@
* Add support for import aliasing: @import utils.math as M@
* Integrate with the main program parser
* Add tests for edge cases (empty files, invalid paths, permission errors)

= See Also

* "Parser.Program" - Main program parser
* "Grammar.Program" - Program AST definitions
* "Grammar.Type" - Type system definitions
-}

module Parser.Program.Import
  ( importDecl
  , processImports
  , ImportError(..)
  , parseProgram
  , mergePrograms
  ) where

import Grammar.Program
import Grammar.Type (TypeDef(..), ConstrDef(..))
import Utils (Name)

import Text.Megaparsec
import qualified Parser.Program as PP (program)
import Data.Void (Void)
import qualified Data.Text as T
import qualified Data.Text.IO as TIO
import Parser.Utils.Utils
import Data.Char
import System.FilePath ((</>), takeDirectory, normalise)
import System.Directory (doesFileExist)

-- | Represents errors that can occur during import processing
--
-- = ⚠️  AI-Generated - Not Yet Human-Reviewed
--
-- Each error type captures specific failure modes in the import system.
-- All errors implement 'Eq' and 'Show' for testing and debugging.
--
-- == Error Types
--
-- * 'FileNotFound': Occurs when an import path doesn't resolve to an existing file
-- * 'CircularImport': Occurs when imports form a cycle (A imports B imports A)
-- * 'ParseError': Occurs when an imported file has syntax errors
-- * 'DuplicateDefinition': Occurs when two imports define the same name
--
-- == Examples
--
-- @
-- -- File not found error
-- FileNotFound "utils\/missing.moo"
-- 
-- -- Circular import chain
-- CircularImport ["main.moo", "utils.moo", "helpers.moo", "main.moo"]
-- 
-- -- Parse error in imported file
-- ParseError "lib\/broken.moo" "unexpected token at line 5"
-- 
-- -- Name conflict between imports
-- DuplicateDefinition "function 'add'" "math.moo" "algebra.moo"
-- @
data ImportError
  = FileNotFound FilePath
    -- ^ The imported file doesn't exist at the resolved path.
    -- Contains the full resolved file path that was not found.
    
  | CircularImport [FilePath]
    -- ^ A circular import dependency was detected.
    -- Contains the full chain of imports showing the cycle.
    -- The last element will be the same as an earlier element.
    -- Example: @["a.moo", "b.moo", "c.moo", "a.moo"]@
    
  | ParseError FilePath T.Text
    -- ^ The imported file contains syntax errors.
    -- Contains the file path and the formatted parse error message.
    
  | DuplicateDefinition Name FilePath FilePath
    -- ^ Two imports define the same name, causing a conflict.
    -- Contains: the conflicting name (with kind prefix like "function 'add'"),
    -- and the two file paths where it's defined.
    -- Note: File paths currently show @\<unknown file\>@ - tracking pending.
    
  deriving (Eq, Show)

-- | Parse an import declaration from source code
--
-- = ⚠️  AI-Generated - Not Yet Human-Reviewed
--
-- Parses the import statement syntax and returns the file path as a 'String'.
-- The path is not resolved or validated at this stage - that happens during
-- 'processImports'.
--
-- == Syntax
--
-- @
-- import path\/to\/file.moo
-- @
--
-- The @import@ keyword must be followed by a file path. The path can contain:
--
-- * Forward slashes (@\/@) for directory separators
-- * Dots (@.@) for file extensions and relative paths (@..@, @.@)
-- * Hyphens (@-@) and underscores (@_@) in file names
-- * Alphanumeric characters (@a-z@, @A-Z@, @0-9@)
--
-- == Examples
--
-- >>> parse importDecl "" "import std/list.moo"
-- Right "std/list.moo"
--
-- >>> parse importDecl "" "import ../utils/math.moo"
-- Right "../utils/math.moo"
--
-- >>> parse importDecl "" "import lib/data/tree.moo"
-- Right "lib/data/tree.moo"
--
-- == Error Cases
--
-- >>> parse importDecl "" "import"
-- Left ... -- Missing path
--
-- >>> parse importDecl "" "import path with spaces.moo"
-- Left ... -- Spaces not allowed in paths
--
-- == Implementation Notes
--
-- * Uses 'keyword' to parse the @import@ keyword
-- * Uses 'lexeme' to consume trailing whitespace
-- * Uses 'takeWhile1P' to parse the path (at least one character required)
-- * Returns the path as a 'FilePath' ('String')
-- * The 'isPathChar' predicate uses 'any' for elegant condition checking
importDecl :: Parser FilePath
importDecl = do
  _ <- keyword "import"
  path <- lexeme importPath
  pure $ T.unpack path
  where
    -- Parse a file path (allows /, ., -, _, alphanumeric)
    importPath = takeWhile1P (Just "import path") isPathChar

    -- Check if a character is valid in an import path
    isPathChar :: Char -> Bool
    isPathChar c = any ($ c) 
      [ (`elem` ['/', '.', '-', '_'])  -- Path separators and special chars
      , isAsciiLower                    -- Lowercase letters
      , isAsciiUpper                    -- Uppercase letters
      , isDigit                         -- Digits
      ]

-- | Process a list of imports and merge them into a base program
--
-- = ⚠️  AI-Generated - Not Yet Human-Reviewed
--
-- This is the main entry point for the import system. It takes a list of
-- import paths (as returned by 'importDecl'), resolves them, parses each
-- file recursively, and merges all definitions into a single program.
--
-- == Algorithm
--
-- For each import path:
--
-- 1. Resolve the path relative to the current file using 'resolveImportPath'
-- 2. Check if the path is already being processed (circular import check)
-- 3. Verify the file exists using 'doesFileExist'
-- 4. Read and parse the file using 'parseProgram'
-- 5. Recursively process any imports in that file
-- 6. Merge definitions using 'mergePrograms' (with conflict detection)
-- 7. Continue with remaining imports
--
-- == Parameters
--
-- [@currentFile@]: The file path of the file being parsed. Used to resolve
--                  relative import paths. Should be an absolute or normalized path.
--
-- [@imports@]: List of import paths as strings (e.g., @["std\/list.moo", "utils\/math.moo"]@).
--              These are relative to @currentFile@.
--
-- [@baseProg@]: The program to merge imports into. Usually starts as an empty program
--               or a program with just the definitions from the current file.
--
-- == Return Value
--
-- Returns @IO (Either ImportError Program)@:
--
-- * @Right prog@: All imports processed successfully, merged program returned
-- * @Left err@: An error occurred (file not found, parse error, etc.)
--
-- == Examples
--
-- @
-- -- Process imports for main.moo
-- result <- processImports "src\/main.moo" 
--                          ["utils\/list.moo", "utils\/math.moo"]
--                          emptyProgram
-- case result of
--   Right program -> putStrLn "All imports processed!"
--   Left err      -> print err
-- @
--
-- == Error Handling
--
-- Can return any of the 'ImportError' types:
--
-- * 'FileNotFound' if any import path doesn't exist
-- * 'CircularImport' if imports form a cycle
-- * 'ParseError' if any file has syntax errors
-- * 'DuplicateDefinition' if imports have name conflicts
--
-- == Implementation Notes
--
-- This function is a thin wrapper around 'processImports'' that initializes
-- the visited set to empty (@[]@). The actual work is done in the internal
-- helper function.
processImports :: FilePath          -- ^ Current file path (for resolving relative imports)
               -> [FilePath]        -- ^ List of import paths to process
               -> Program           -- ^ Base program to merge into
               -> IO (Either ImportError Program)
processImports currentFile imports baseProg = do
  processImports' currentFile imports baseProg []

-- | Internal helper function with circular dependency tracking
--
-- = ⚠️  AI-Generated - Not Yet Human-Reviewed
--
-- This is the recursive workhorse of the import system. It maintains a list
-- of visited files to detect circular imports and processes each import in sequence.
--
-- == Base Case
--
-- When the import list is empty (@[]@), returns the accumulated program:
--
-- @
-- processImports' _ [] prog _ = pure $ Right prog
-- @
--
-- == Recursive Case
--
-- When there are imports to process, follows this algorithm:
--
-- 1. __Resolve Path__: Convert relative path to absolute using 'resolveImportPath'
-- 2. __Check Circular__: If @resolvedPath@ is in @visited@, return 'CircularImport'
-- 3. __Check Exists__: If file doesn't exist, return 'FileNotFound'
-- 4. __Read File__: Read file contents using 'TIO.readFile'
-- 5. __Parse File__: Parse using 'parseProgram', return 'ParseError' on failure
-- 6. __Merge Programs__: Merge using 'mergePrograms', return 'DuplicateDefinition' on conflict
-- 7. __Recurse__: Process remaining imports with updated program and visited set
--
-- == Parameters
--
-- [@currentFile@]: The file currently being processed. Used for path resolution.
--
-- [@imports@]: Remaining import paths to process.
--
-- [@prog@]: Accumulated program with all definitions so far.
--
-- [@visited@]: List of file paths already processed. Used for circular import detection.
--              Includes the full path from the original file to the current import chain.
--
-- == Circular Import Detection
--
-- The @visited@ list maintains the entire import chain. When we detect that
-- @resolvedPath `elem` visited@, we return the full chain including the duplicate:
--
-- @
-- CircularImport (visited ++ [resolvedPath])
-- @
--
-- This shows users exactly where the cycle occurs. For example:
--
-- @
-- ["main.moo", "utils.moo", "helpers.moo", "main.moo"]
--                                           ^^^^^^^^ cycle!
-- @
--
-- == Error Propagation
--
-- All errors are propagated immediately using @Either@. The function short-circuits
-- on the first error encountered, which means later imports won't be processed if
-- an earlier one fails.
--
-- == State Threading
--
-- Note how state is threaded through the recursion:
--
-- * @resolvedPath@ becomes the new @currentFile@ (for resolving nested imports)
-- * @rest@ becomes the new import list (one item consumed)
-- * @mergedProg@ becomes the new accumulated program
-- * @resolvedPath:visited@ becomes the new visited set (file added)
--
-- == Implementation Notes
--
-- * Uses 'IO' for file system operations ('doesFileExist', 'TIO.readFile')
-- * Uses 'Either' for error handling (no exceptions thrown)
-- * Processes imports sequentially (not parallel) to maintain deterministic order
-- * Each imported file can itself have imports (recursive)
processImports' :: FilePath
                -> [FilePath]
                -> Program
                -> [FilePath]  -- ^ Already processed files (for cycle detection)
                -> IO (Either ImportError Program)
processImports' _ [] prog _ = pure $ Right prog

processImports' currentFile (importPath:rest) prog visited = do
  -- Step 1: Resolve the import path relative to current file
  let resolvedPath = resolveImportPath currentFile importPath

  -- Step 2: Check for circular imports
  if resolvedPath `elem` visited
    then pure $ Left $ CircularImport (visited ++ [resolvedPath])
    else do
      -- Step 3: Check if file exists
      fileExists <- doesFileExist resolvedPath
      if not fileExists
        then pure $ Left $ FileNotFound resolvedPath
        else do
          -- Step 4: Read and parse the imported file
          content <- TIO.readFile resolvedPath
          case parseProgram resolvedPath content of
            Left err -> pure $ Left $ ParseError resolvedPath (T.pack $ errorBundlePretty err)
            Right importedProg -> do
              -- Step 5: Merge imported program with current program
              case mergePrograms prog importedProg of
                Left conflict -> pure $ Left conflict
                Right mergedProg -> 
                  -- Step 6: Recurse with updated state
                  processImports' resolvedPath rest mergedProg (resolvedPath:visited)

-- | Resolve an import path relative to the current file
--
-- = ⚠️  AI-Generated - Not Yet Human-Reviewed
--
-- Converts a relative import path to an absolute (or normalized) path by
-- resolving it relative to the directory containing the current file.
--
-- == Algorithm
--
-- 1. Extract the directory of @currentFile@ using 'takeDirectory'
-- 2. Combine it with @importPath@ using the path separator '<\/>'
-- 3. Normalize the result using 'normalise' to resolve @..@ and @.@
--
-- == Examples
--
-- === Relative sibling import
--
-- @
-- resolveImportPath "src\/main.moo" "utils.moo"
-- -- Result: "src\/utils.moo"
-- @
--
-- === Subdirectory import
--
-- @
-- resolveImportPath "src\/main.moo" "lib\/list.moo"
-- -- Result: "src\/lib\/list.moo"
-- @
--
-- === Parent directory import
--
-- @
-- resolveImportPath "src\/util\/helper.moo" "..\/core.moo"
-- -- Result: "src\/core.moo"
-- @
--
-- === Multiple parent traversal
--
-- @
-- resolveImportPath "src\/a\/b\/c.moo" "..\/..\/d.moo"
-- -- Result: "src\/a\/d.moo"
-- @
--
-- === Already absolute path (rare)
--
-- @
-- resolveImportPath "src\/main.moo" "\/usr\/lib\/moo\/std.moo"
-- -- Result: "\/usr\/lib\/moo\/std.moo" (normalized)
-- @
--
-- == Path Normalization
--
-- The 'normalise' function from @System.FilePath@:
--
-- * Removes redundant separators: @a\/\/b@ → @a\/b@
-- * Resolves @.@ (current directory): @a\/.\/b@ → @a\/b@
-- * Resolves @..@ (parent directory): @a\/b\/..\/c@ → @a\/c@
-- * Handles platform-specific path conventions
--
-- == Error Handling
--
-- This function is pure and cannot fail. However, the resulting path:
--
-- * May not exist on disk (checked later by 'processImports'')
-- * May escape the project directory if @..@ is used excessively
-- * May refer to system paths if an absolute path is given
--
-- These issues are detected in later stages of import processing.
--
-- == Platform Compatibility
--
-- Uses @System.FilePath@ which handles platform differences:
--
-- * Unix\/Linux: Uses @\/@ as separator
-- * Windows: Uses @\\@ as separator
-- * Works correctly on both platforms
--
-- == Implementation Notes
--
-- * Uses 'let' binding for clarity
-- * Pure function (no IO)
-- * Relies on @System.FilePath@ library functions
-- * Thread-safe and referentially transparent
resolveImportPath :: FilePath -> FilePath -> FilePath
resolveImportPath currentFile importPath = 
  let currentDir = takeDirectory currentFile
  in normalise $ currentDir </> importPath

-- | Merge two programs, checking for definition conflicts
--
-- = ⚠️  AI-Generated - Not Yet Human-Reviewed
--
-- Combines definitions from two programs into one, validating that no names
-- conflict. This is used when merging an imported program with the base program.
--
-- == Conflict Detection Rules
--
-- A conflict occurs when the same name appears in both programs for:
--
-- * __Type definitions__: Two types with the same name
-- * __Data constructors__: Two constructors with the same name (even in different types)
-- * __Global variables__: Two globals with the same name
-- * __Constants__: Two constants with the same name
-- * __Functions__: Two functions with the same name
--
-- If any conflict is detected, returns @Left (DuplicateDefinition ...)@.
--
-- == Merging Strategy
--
-- If no conflicts exist, simply concatenates all definition lists:
--
-- @
-- Program
--   (pGlobals prog1 ++ pGlobals prog2)
--   (pConsts prog1 ++ pConsts prog2)
--   (pFuns prog1 ++ pFuns prog2)
--   (pTypes prog1 ++ pTypes prog2)
-- @
--
-- This means:
--
-- * Order is preserved (prog1 definitions come before prog2)
-- * No deduplication (same definition in both = error)
-- * No shadowing (both definitions would be visible)
--
-- == Examples
--
-- === Successful merge (no conflicts)
--
-- @
-- prog1 = Program
--   { pGlobals = [Global "x" TInt (LInt 5)]
--   , pConsts = []
--   , pFuns = [FunDef "foo" [] TInt [...]]
--   , pTypes = []
--   }
--
-- prog2 = Program
--   { pGlobals = [Global "y" TInt (LInt 10)]
--   , pConsts = []
--   , pFuns = [FunDef "bar" [] TInt [...]]
--   , pTypes = []
--   }
--
-- mergePrograms prog1 prog2
-- -- Result: Right (Program with both x and y, both foo and bar)
-- @
--
-- === Failed merge (function conflict)
--
-- @
-- prog1 = Program { ..., pFuns = [FunDef "add" ...], ... }
-- prog2 = Program { ..., pFuns = [FunDef "add" ...], ... }
--
-- mergePrograms prog1 prog2
-- -- Result: Left (DuplicateDefinition "function 'add'" ...)
-- @
--
-- === Failed merge (constructor conflict)
--
-- @
-- prog1 = Program { ..., pTypes = [TypeDef "T1" [] [ConstrDef "None" []]], ... }
-- prog2 = Program { ..., pTypes = [TypeDef "T2" [] [ConstrDef "None" []]], ... }
--
-- mergePrograms prog1 prog2
-- -- Result: Left (DuplicateDefinition "constructor 'None'" ...)
-- @
--
-- == Limitations
--
-- ⚠️  __File origin tracking not yet implemented__
--
-- The 'DuplicateDefinition' error currently shows @\<unknown file\>@ for both
-- file paths because 'Program' doesn't track where definitions come from.
--
-- To fix this, we would need to either:
--
-- * Extend 'Program' with metadata: @data Program = Program { ..., pSource :: FilePath }@
-- * Pass file paths separately: @mergePrograms :: FilePath -> Program -> FilePath -> Program -> ...@
-- * Use a wrapper type: @data SourcedProgram = SourcedProgram FilePath Program@
--
-- This is marked as a future improvement.
--
-- == Error Messages
--
-- Error messages include the kind of definition and the name:
--
-- * @"type 'MyType'"@
-- * @"constructor 'None'"@
-- * @"global 'myVar'"@
-- * @"const 'PI'"@
-- * @"function 'myFunc'"@
--
-- == Implementation Details
--
-- === Why check constructors separately?
--
-- Constructors from different types must still be unique. In Moo, you can't have:
--
-- @
-- type Option[a] := None | Some(a)
-- type Result[a, b] := None | Error(b)  -- Error! 'None' already used
-- @
--
-- That's why we extract all constructor names across all types and check them.
--
-- === Monadic do notation
--
-- Uses @Either@ monad's @do@ notation for sequencing checks:
--
-- @
-- do
--   checkDuplicates "type" ...
--   checkDuplicates "constructor" ...
--   ...
--   Right $ Program ...
-- @
--
-- If any check returns @Left@, the remaining checks are skipped.
--
-- === Helper function: checkDuplicates
--
-- @
-- checkDuplicates :: String -> [Name] -> [Name] -> Either ImportError ()
-- @
--
-- * Filters @names1@ for items that also appear in @names2@
-- * Returns @Right ()@ if no duplicates found
-- * Returns @Left (DuplicateDefinition ...)@ on first duplicate found
-- * Uses @case@ instead of @if null@ for pattern matching
--
-- == Performance Considerations
--
-- * Uses '(++)'  for list concatenation (O(n) where n is length of first list)
-- * Uses 'elem' for membership check (O(n) where n is length of list)
-- * For large programs with many imports, consider using @Data.Set@ for faster lookups
--
-- Current complexity for each check: O(n × m) where n and m are list sizes.
-- Total complexity: O(total definitions squared) in worst case.
--
-- For small to medium programs (hundreds of definitions), this is acceptable.
--
-- == See Also
--
-- * 'processImports'' - Calls this function to merge imported programs
-- * 'ImportError' - Error types that can be returned
-- * "Grammar.Program" - Definition of 'Program', 'TypeDef', 'FunDef', etc.
mergePrograms :: Program -> Program -> Either ImportError Program
mergePrograms prog1 prog2 = do
  -- Check for duplicate type names
  checkDuplicates "type" (map tName (pTypes prog1)) (map tName (pTypes prog2))
  
  -- Check for duplicate constructor names across all types
  let constrs1 = concatMap (\t -> map cName (tConstrs t)) (pTypes prog1)
  let constrs2 = concatMap (\t -> map cName (tConstrs t)) (pTypes prog2)
  checkDuplicates "constructor" constrs1 constrs2
  
  -- Check for duplicate global names
  checkDuplicates "global" (map gName (pGlobals prog1)) (map gName (pGlobals prog2))
  
  -- Check for duplicate const names
  checkDuplicates "const" (map kName (pConsts prog1)) (map kName (pConsts prog2))
  
  -- Check for duplicate function names
  checkDuplicates "function" (map fName (pFuns prog1)) (map fName (pFuns prog2))
  
  -- If all checks pass, merge the programs
  Right $ Program
    (pGlobals prog1 ++ pGlobals prog2)
    (pConsts prog1 ++ pConsts prog2)
    (pFuns prog1 ++ pFuns prog2)
    (pTypes prog1 ++ pTypes prog2)
  where
    -- | Check for duplicate names between two lists
    --
    -- Takes a kind label (for error messages), two name lists, and returns
    -- either success or a duplicate definition error.
    --
    -- @
    -- checkDuplicates "function" ["foo", "bar"] ["baz", "bar"]
    -- -- Result: Left (DuplicateDefinition "function 'bar'" ...)
    -- @
    checkDuplicates :: String -> [Name] -> [Name] -> Either ImportError ()
    checkDuplicates kind names1 names2 =
      case filter (`elem` names2) names1 of
        [] -> Right ()
        (dup:_) -> Left $ DuplicateDefinition 
          (T.pack kind <> " '" <> dup <> "'")
          "<unknown file>"  -- ⚠️  TODO: Track file origins for better errors
          "<unknown file>"

-- | Parse a complete Moo program from text content
--
-- = ⚠️  AI-Generated - Not Yet Human-Reviewed
--
-- This function bridges the import system with the main program parser. It
-- takes file contents as 'Text' and parses it into a 'Program' AST using
-- the main parser from "Parser.Program".
--
-- == Purpose
--
-- This function serves as the connection point between:
--
-- * The import system (this module)
-- * The main program parser ("Parser.Program")
--
-- It's used by 'processImports'' to parse imported files.
--
-- == Parameters
--
-- [@filepath@]: The file path for error reporting. Used by Megaparsec to show
--               where parse errors occurred. Should match the file that @content@
--               came from.
--
-- [@content@]: The complete text content of the file to parse. Typically obtained
--              via 'TIO.readFile'.
--
-- == Return Value
--
-- Returns @Either (ParseErrorBundle T.Text Void) Program@:
--
-- * @Right program@: Parsing succeeded, returns the parsed program AST
-- * @Left errorBundle@: Parsing failed, returns detailed error information
--
-- The 'ParseErrorBundle' includes:
--
-- * Line and column numbers where the error occurred
-- * The unexpected token or EOF
-- * What was expected at that position
-- * Context around the error
--
-- == Examples
--
-- === Successful parse
--
-- @
-- content <- TIO.readFile "example.moo"
-- case parseProgram "example.moo" content of
--   Right prog -> print prog
--   Left err -> putStrLn $ errorBundlePretty err
-- @
--
-- === Parse error handling
--
-- @
-- let invalidCode = "fun broken( -> Int := 42"
-- case parseProgram "test.moo" invalidCode of
--   Right _ -> error "Should have failed!"
--   Left bundle -> do
--     -- Convert error bundle to pretty-printed string
--     putStrLn $ errorBundlePretty bundle
--     -- Output might be:
--     -- test.moo:1:13:
--     --   |
--     -- 1 | fun broken( -> Int := 42
--     --   |             ^
--     -- unexpected '->'
--     -- expecting ')', parameter name, or ':'
-- @
--
-- == Integration with Import System
--
-- This function is called by 'processImports'' for each imported file:
--
-- @
-- content <- TIO.readFile resolvedPath
-- case parseProgram resolvedPath content of
--   Left err -> pure $ Left $ ParseError resolvedPath (T.pack $ errorBundlePretty err)
--   Right importedProg -> ...
-- @
--
-- The error bundle is converted to 'Text' using 'errorBundlePretty' and
-- wrapped in 'ParseError'.
--
-- == Implementation Notes
--
-- * Delegates to 'PP.program' from "Parser.Program"
-- * Uses 'runParser' from Megaparsec to run the parser
-- * Pure function (no IO)
-- * Type parameters: @T.Text@ (input type), @Void@ (custom error type - none)
--
-- == Why qualified import?
--
-- We import "Parser.Program" qualified as @PP@ to avoid naming conflicts:
--
-- * This module might want its own @program@ function later
-- * Makes it clear we're using the external parser
-- * Prevents accidental shadowing
--
-- == Error Type: Void
--
-- The error type is 'Void' which means:
--
-- * No custom error types are used
-- * Only standard Megaparsec errors can occur
-- * 'Void' is uninhabited (no values of this type exist)
-- * This is the default for simple parsers
--
-- == Performance
--
-- * Parser performance depends on "Parser.Program" implementation
-- * No caching - same file parsed multiple times if imported multiple times
-- * Future optimization: cache parsed programs in a @Map FilePath Program@
--
-- == See Also
--
-- * 'processImports'' - Uses this function to parse imported files
-- * "Parser.Program" - The main program parser being wrapped
-- * 'ParseErrorBundle' - Megaparsec's error type
-- * 'errorBundlePretty' - Converts error bundle to human-readable string
parseProgram :: FilePath -> T.Text -> Either (ParseErrorBundle T.Text Void) Program
parseProgram filepath content = 
  runParser PP.program filepath content

{-|
= Implementation Checklist

== ✅ Completed Tasks

[✅] __1. Add dependencies to Moo.cabal__
     
     * Added @filepath@ dependency for path manipulation
     * Added @directory@ dependency for file system operations
     * Dependencies: @filepath-1.4.301.0@, @directory-1.3.8.5@

[✅] __2. Implement file I/O__
     
     * 'doesFileExist' - Check if imported file exists
     * 'TIO.readFile' - Read file contents as Text
     * Proper error handling with 'FileNotFound'

[✅] __3. Implement path resolution__
     
     * 'resolveImportPath' - Resolve relative paths correctly
     * Uses 'takeDirectory', '<\/>', 'normalise'
     * Handles @..\/@ (parent) and @.\/@ (current) correctly
     * Platform-independent path handling

[✅] __4. Implement conflict detection in mergePrograms__
     
     * Checks duplicate type names via @tName@
     * Checks duplicate constructor names via @cName@ (all types)
     * Checks duplicate global names via @gName@
     * Checks duplicate const names via @kName@
     * Checks duplicate function names via @fName@
     * Returns 'DuplicateDefinition' with kind and name
     
     ⚠️  File origin tracking shows @\<unknown file\>@ - needs future work

[✅] __5. Connect to Parser.Program__
     
     * Created 'parseProgram' function
     * Uses qualified import: @import qualified Parser.Program as PP (program)@
     * Properly integrated with 'processImports''
     * No circular dependencies

[✅] __6. Add circular import prevention__
     
     * Maintains @visited@ list of processed files
     * Checks @resolvedPath \`elem\` visited@ before processing
     * Returns 'CircularImport' with full chain
     * Properly threads visited set through recursion

== 📋 Pending Tasks

[📋] __7. Integration with main parser__
     
     * Add import parsing to "Parser.Program"
     * Call 'processImports' from main program parser
     * Pass current file path through parser context
     * Handle imports at beginning of file

[📋] __8. Performance optimization: Caching__
     
     * Cache parsed files to avoid re-parsing
     * Use @Map FilePath Program@ for cache
     * Thread cache through 'processImports''
     * Consider LRU eviction for large projects

[📋] __9. Enhanced error messages__
     
     * Track file origins in 'Program' or separate structure
     * Show actual file paths in 'DuplicateDefinition' errors
     * Add source location info to all definitions
     * Consider using @data SourcedProgram = SourcedProgram FilePath Program@

[📋] __10. Advanced features__
     
     * Selective imports: @import utils.math (add, multiply)@
     * Import aliasing: @import utils.math as M@
     * Export control: @export (add, subtract)@ in modules
     * Private definitions (not exported)

[📋] __11. Testing__
     
     * Unit tests for path resolution
     * Unit tests for conflict detection
     * Integration tests for recursive imports
     * Test circular import detection
     * Test error messages
     * Test edge cases (empty files, missing files, permissions)

[📋] __12. Documentation improvements__
     
     * Add usage examples to main module docs
     * Document import resolution algorithm formally
     * Add diagrams showing import chains
     * Document performance characteristics
     * Add troubleshooting guide

== ⚠️  Known Limitations

* File origin tracking not implemented ('DuplicateDefinition' shows @\<unknown file\>@)
* No import caching (same file parsed multiple times)
* No selective imports or aliasing
* Not yet integrated with main parser
* No export control
* Sequential import processing (not parallel)

== 🎯 Next Steps

The most important next steps are:

1. __Integration__: Connect to "Parser.Program" so imports actually work
2. __Testing__: Add comprehensive test suite
3. __File tracking__: Implement proper origin tracking for better errors

-}
